### ISSUE TITLE
Mod installation for higher player count

### ISSUE THREAD

**Issue by TheWorkingDeveloper** [Nimdy/Dedicated_Valheim_Server_Script#107]
Is it possible to install mods on this server, and if so, how?
I'd like to try play with around 12 people and apparently there's a mod to do so.

**Comment by VP-EN** [comment]
I don't think Nimdy offers support for mods.. But a quick guide:
You'll need to install the [BepInEx Pack for Valheim](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) both on the client and the server. 

For the server, you should then use (and edit) the `start_server_bepinex.sh` for starting the server, instead of the one used by the `start_valheim.sh` installed by this script.

If you're running the server as a service, you should also edit the service file `/etc/systemd/system/valheimserver.service` to use the `start_server_bepinex.sh` instead of the `start_valheim.sh`

Then you would need to install a mod for higher player count like [this one](https://valheim.thunderstore.io/package/Valdream/MaxPlayerModifier/). 

**Disclaimer:** I haven't tested the player count mod for myself.

**Comment by Nimdy** [comment]
Thanks VP-EN!!!

yeah in the future I will support mods... just not at this time.
