### ISSUE TITLE
Lag in areas with too many players

### ISSUE THREAD

**Issue by ramonsaraiva** [Nimdy/Dedicated_Valheim_Server_Script#113]
Prob related to https://github.com/Nimdy/Dedicated_Valheim_Server_Script/issues/80

We're experiencing a massive lag when too many people (i.e. 8 players) are in the same spot.
I'm using a t2.medium instance at AWS (2gb RAM 2vCPU), CPU is staying ~18% and memory usage ~50%.

I don't believe this is related to hardware but maybe some capped upload/download rates?

Anyone else facing this issue as well? Feels quite a bit unplayable in boss fights etcetera.

**Comment by Nimdy** [comment]
This is not script related and is a Offiical Valheim issue.

We recommend 4CPU 8GB ram.

Min 2CPU 4GB RAM

But at some point you will need more resources.  Think Minecraft.  Sure you might be able to get the game running and have your friends playing with you, with little resources.  However, as you start building, exploring... the need for resources will grow.  This need coupled with the issues from IronGate = bad.  This is because the game was never designed to do what is happening now.  This is a good thing but also a bad thing for the players.  The good reason is because IronGate will make improvements since they sold over 5 million copies at this point in time.  The bad is we have to wait.

You are correct on the upload/download limit caps.

But you also need to look at it like this.

Valheim uses a flatfile database.... The reason for the cap is for player do not jack up the write/processing/operations of the flatfile database.  Until IronGate moves to a new way of storing data or adds a better database manage process, I highly recommend leaving the cap alone.  Yes, you can do this with mods.  I do not support this yet. The amount of questions answered because people have not read the WIKI, will only continue to pill up because of the issues that may arise from adding mods.

In the future, we will be adding this but the game needs to be better.

**Comment by ramonsaraiva** [comment]
Cool, thanks for the detailed explanation @Nimdy. Appreciate it.
