### ISSUE TITLE
cannot use old map

### ISSUE THREAD

**Issue by chandler0714** [Nimdy/Dedicated_Valheim_Server_Script#131]
I try to following your guide to replace map. but there is not working. still new map... and i have double check winscp nothing wrong... could u help me out this issue? thx

**Comment by Nimdy** [comment]
then there is something else wrong. Corrupt maps can happen... and they happen a lot.

but mostly people are unsucccessful at this because they do not stop the valheim services before transferring the files and later they forget to set chown steam:steam permissions to the new .db and .fwl... additionally, they forget to validate their start_valheim.sh file and make sure the world name matches... the .db and .fwl files.   For the Loki do not change your .db and .fwl files if you do not know what you are doing.... it doesnt work by just renaming them.  

Again 100% walkthrough... the steps are fail proof.

**Comment by chandler0714** [comment]
> 
> 
> then there is something else wrong. Corrupt maps can happen... and they happen a lot.
> 
> but mostly people are unsucccessful at this because they do not stop the valheim services before transferring the files and later they forget to set chown steam:steam permissions to the new .db and .fwl... additionally, they forget to validate their start_valheim.sh file and make sure the world name matches... the .db and .fwl files. For the Loki do not change your .db and .fwl files if you do not know what you are doing.... it doesnt work by just renaming them.
> 
> Again 100% walkthrough... the steps are fail proof.

the map is done, but there have no building which is i was done. is there only two file need to copy? i saw db.old and fwl.old but dont know what is that for.. T~T

**Comment by Nimdy** [comment]
the old files are created by IronGate, During their save checks, I believe... nothing that the script creates
