### ISSUE TITLE
Name with special characters [FEATURE]

### ISSUE THREAD

**Issue by danz00** [Nimdy/Dedicated_Valheim_Server_Script#176]
Is that possible to implement that? 
Im trying to set a name with ! or html codes like <color=> but didn't worked
after the change I back to change the name and the "old name" are blank

**Comment by Nimdy** [comment]
yeah I will not be adding support for this.

You will have to do some serious ignore rules in the config file for start_valheim.sh

for  example: "<font color=\"red\">My Public Name</font>"

I dont have the time to play around with what works and what doesnt but if you come up with something and post a how-to I will add it.

The issues will come into play later, when you want to use V+ or another modding configuration.  Because then you need to see if that works in their scripts.

It can be done but needs to have a lot of testing on what works and what doesnt work.

**Comment by Nimdy** [comment]
marked in things to do
