### ISSUE TITLE
Feature Request: World Chooser

### ISSUE THREAD

**Issue by Pendora2017** [Nimdy/Dedicated_Valheim_Server_Script#18]
It would be really nice if you could switch between different worlds via a menu (perhaps with the help of a .sh script) after the SSH login.

e.g.
[1] Choose a world to start | or [1] Choose a world for autostart
[2] Create a new world
[3] Delete a world

After a choosen world was started the script jumps back to its start and display which world is running and if you would like to change to another world 

e.g.
Now running world: 'test1' (Uptime: 10h 15m)

[1] Choose an other world to start (and force world shutdown test1)
[2] Stop Server

So you could play with different friends on different worlds but everything on one server
(I know that only one world can be active at a time)

**Comment by Nimdy** [comment]
Nice! idea! Thanks... Let's see what we can do...

**Comment by Pendora2017** [comment]
One more idea in addition:

Add an entry for "Backup & Restore" and "Update Valheim-Server"

**Comment by Nimdy** [comment]
> One more idea in addition:
> 
> Add an entry for "Backup & Restore" and "Update Valheim-Server"

its in the new menu system now but only as a backup and restore function... It could be used as a world switcher... basically the same process but the valheim_start.sh -world would need to be changed to reflect the different world names. 

We can add this later as a advance feature....

**Comment by Nimdy** [comment]
added to projects

**Comment by dreamalligator** [comment]
Does the world changer refresh the server as well? Or do we have to manually do that.

**Comment by Nimdy** [comment]
Right now, that is manual via

```sh
nano /home/steam/valheimserver/start_valheim.sh
```

I didnt enable/build the function for the menu system because I fear people will break their games.... or rename their .db and .fwl files (which nobody should do but they do it anyways) {I moved over my world files and started the game but everything is blank -issues-}

The future menu GUI will have this enable :)  I am only one person and I am grateful for the help I have been receiving on this fun project.
