### ISSUE TITLE
[FEATURE] Service account should be configurable.

### ISSUE THREAD

**Issue by unixtreme** [Nimdy/Dedicated_Valheim_Server_Script#260]
**Is your feature request related to a problem? Please describe.**
The account may be already in the system or in use for something else.
It also makes multiple instances easier to manage.

**Describe the solution you'd like**
Currently it can be hardcoded in the script but it would be ideal to prompt for an account name.

**Describe alternatives you've considered**
A config file, if something like JQ is baked into the suite then the option for json config files opens up, which would make it easier to manage custom settings as well as unattended installations (e.g. cloud instance/container re-deployments).

**Comment by Nimdy** [comment]
I understand your point.  This is aim for people who do not having any knowledge about Linux.  I designed with this in mind and the first menu system had people put whatever they wanted.  The amount of time I spent helping people because they could not edit a configuration file correctly or input from a prompt correctly, was too high.

After the launch of the new Njord menu, we will be adding a web gui installer and other install methods for advance users. Please stick around and help out :)
