### ISSUE TITLE
listing of ports [BUG]

### ISSUE THREAD

**Issue by skynett81** [Nimdy/Dedicated_Valheim_Server_Script#273]
**Describe the bug**
it does not list corectly  ... its an / too much after valheimserver

Server Port: Can't open /home/steam/valheimserver//start_valheim_.sh: No such file or directory.

**Comment by skynett81** [comment]
its in the njordmenu.sh

**Comment by Nimdy** [comment]
no something was missing from your configuration file. 

this: Server Port: Can't open /home/steam/valheimserver//start_valheim_.sh: No such file or directory.

should look like this:

Server Port: Can't open /home/steam/valheimserver/Whateverworldname/start_valheim_whateverworldname.sh: No such file or directory.

**Comment by Nimdy** [comment]
Wondering what your configuration file looks like.

show me your start_valheim.sh file

**Comment by brink668** [comment]
I am having the same issue.  


║ Valheim Official Build: 6766400
║ Local Valheim Install:  6766400
║ Current Valheim Instance:
║ Server Name:
║ Internet:    Connected
║ External IP: 159.x.x.x
║ Internal IP: 159.x.x.x 10.132.0.2
**║ Server Port: Can't open /home/steam/valheimserver//start_valheim_.sh: No such file or directory.**

The file actually exists but the path looks to be searching for "//" to double slashes instead of 1?

![2021-06-16 09_05_02-mRemoteNG - confCons xml - valheim](https://user-images.githubusercontent.com/4675715/122224364-092dd100-ce82-11eb-9c11-6b2f81872cba.png)

### Redacted start_valheim.sh file
![image](https://user-images.githubusercontent.com/4675715/122224642-4db96c80-ce82-11eb-8857-9a5ce0521bac.png)

**Comment by Nimdy** [comment]
did you run the upgrade from the njordmenu.sh ? option 0000 if shown

**Comment by Nimdy** [comment]
![image](https://user-images.githubusercontent.com/16698453/122359106-8f671780-cf55-11eb-9b68-e4d1f782dd34.png)

**Comment by brink668** [comment]
I did upgrade using the NordMenu.  I ended up just reinstalling on another server.  Looked like I had a pathing issue during the original setup.

**Comment by Nimdy** [comment]
> I did upgrade using the NordMenu. I ended up just reinstalling on another server. Looked like I had a pathing issue during the original setup.

Sweeet glad it worked out!  Let me know if you need anything else!
