### ISSUE TITLE
Issue with ports

### ISSUE THREAD

**Issue by Daguima-dag** [Nimdy/Dedicated_Valheim_Server_Script#51]
Hi! First of all thanks for your amazing work.
I asked this on Youtube but thought it best to ask it here. So, I followed your tutorial and have the server running on Digitalocean. But for some reason I just can't get port 2456 open. Port 2457 is open but 2456 and 2458 are closed (checked with the port checker you linked). 
Is there anything more to opening ports in DigitalOcean than editing the YAML file and running "netplan apply"? I tried adding rules to ufw and enabling it, but it didn't make much of a difference. I also tried activating Digitalocean control panel's firewall. Neither worked. I actually was able to connect the game to the server once, but it seemed totally random.

**Comment by Nimdy** [comment]
Same on mine but I have zero issues.

So I am confused why you are experiencing issues.

Our Discord has a lot of people helping each other out on issues out the script.

**Comment by crunchprank** [comment]
I know this issue has been closed, but I've reached out via Discord with no help as of yet. I feel like I'm running into a similar issue as the OP.

I first attempted using `ufw` but quickly realized I'm a lot more familiar with `iptables` so that is what I'm using in the output below. And just to clarify, `ufw` has been disabled:

```
# ufw status
Status: inactive
```

To rule out *any* issues with ports, I went ahead and configured the firewall to allow any traffic on any port on any network interface with any protocol:

```
# iptables -nvL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1063 63659 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 952 packets, 154K bytes)
 pkts bytes target     prot opt in     out     source               destination
```

When looking at the services that are actively listening on ports, I do not see the Valheim server at all:

```
# netstat -ntpl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      572/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      727/sshd: /usr/sbin
tcp6       0      0 :::22                   :::*                    LISTEN      727/sshd: /usr/sbin
```

However when I look at all services and their ports, I do see that port `2457` is active, but not in a `LISTEN` state:

```
# netstat -npl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      572/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      727/sshd: /usr/sbin
tcp6       0      0 :::22                   :::*                    LISTEN      727/sshd: /usr/sbin
udp        0      0 127.0.0.53:53           0.0.0.0:*                           572/systemd-resolve
udp        0      0 0.0.0.0:2457            0.0.0.0:*                           1532/./valheim_serv  < - -
raw6       0      0 :::58                   :::*                    7           570/systemd-network
raw6       0      0 :::58                   :::*                    7           570/systemd-network
```

When I run the Valheim port checking tool on `geekstrom.de`, I see that port `2457` gets the OK, but not `2456` or `2458`.

I have no other external firewall applications such as the built-in tool within the DigitalOcean dashboard.

Some additional information if necessary:

```
Provider: DigitalOcean
OS: Ubuntu 20.04.2 LTS
```

If you have any ideas or input, it would be greatly appreciated.

**Comment by Nimdy** [comment]
type

ufw enable

see if anything changes.

Worst case... PM me in Discord and I will screen share with you and we can do it together and figure out what is really going on.

**Comment by Daguima-dag** [comment]
Hi! Just letting you know that I was able to connect to the server, even though only port 2457 gets the OK. Everything seems to be running fine. I noticed that I could connect to the server once but after logging out it didn't work. But I noticed that if I go back to the first Menu screen and then back to the JOIN IP button, it works. It looks like it's probably a bug with the JOIN IP feature not refreshing after logging out once.
