### ISSUE TITLE
Problem with Ports

### ISSUE THREAD

**Issue by Erater** [Nimdy/Dedicated_Valheim_Server_Script#61]
Hey there,
first of all thanks for the great work you've done to make this all work.

Now to my issue, I installed the server on a local homeserver 2 cpus 8 gb ram nothing special but it should be working for a small group of people. I just managed portforwarding (should be working, same porcedure as for my home Nextcloud). Port scanners says the ports 2456-2458 are closed. Even nmap on the server itself doesn't list these ports as open.
With internal IP i can connect to the server, strange behaviour i think with closed ports. But external no chance even though the ports are forwarded. Any idea about this problem?

**Comment by andrew-canning** [comment]
I believe that's because nmap by default uses TCP scanning and the server uses UDP.  If that's the case you could use "-sU" flag and see if you get the "open | filtered" status.  My guess is that your forwarder inspects the type of level 4 traffic.  An easy way to confirm is to stop the valheim service, start a simple udp server "nc –u –l 2456", and try to connect to it from the client machine "nc -u 192.168.1.123 2456"; then on either machine, just start typing stuff.

**Comment by Erater** [comment]
Hey there,
thanks for the answer, i tried the netcat thing. It's just the same result, via internal ip 192.168.68.115 i can use it, external ip won't work :(. A little bit more information to my network structure, i got 2 networks one behind the other, the first is just for the ISP, the second is my homenetwork, i needed that, so i could further use my mesh routers. On both of these routers the ports 2456-2458 are opened on both protocols. I just can think about that my ISP is blocking the incoming traffic on the port. I got no other idea what is configured wrong.

**Comment by Erater** [comment]
Nevermind, just weird behaviour i guess. Pulled the newest git just to use the new menu and it seems now running. Don't know what was going wrong but it works now. But thanks for the help :D
