### ISSUE TITLE
Fix for multiplayer lag

### ISSUE THREAD

**Issue by lingnaishin** [Nimdy/Dedicated_Valheim_Server_Script#80]
https://indiefaq.com/guides/valheim-fix-for-multiplayer-lag.html?fbclid=IwAR1SyvceZZHOAk3JoG181ojoq-IEiR7--1kwzjBENdaD3jncPNmBWddivuw

hi @Nimdy, I have found an article regarding having many players on a server and causes lag.
This is due to the limit of data per second the game server can upload to players.
Any way we can implement this fix to the script ?

**Comment by Nimdy** [comment]
I will look into it.

Here is what I am wondering though... just guessing.......

The reason for the limit... is because of the way the flatfile database processes data.... and they do not have that process smooth out beyond its current state.

Increase the speed in which player can connect... also increases the amount of data for send and receive. Which in turns means more data for processing to the database. 

Database functions for clean, repair, check...etc...etc might not be able to keep up because of the increased data transfers.

I am just guess here... but I believe this to be one of the major factors at play to prevent corrupted databases.  Lurking the Official Valheim Discord, I continue to read about the issues people are having with corrupted databases.

The only way for me to successful test this theory is to build another dev box and have players on it.

Now it is very possible that a increase to CPU/RAM might benefit the increase allowance for connected players but this is just my initial thought process.

Thoughts?

**Comment by lingnaishin** [comment]
I have tested increasing CPU/RAM from 2/4 to 4/8 and still when there are many players in 1 area, the lag occurs. Items starting to fly around and players unable to execute action in that particular area only.
I was also observing the CPU and RAM usage when the lag occurs and CPU / ram usage did not hit 100%.

**Comment by lingnaishin** [comment]
I will be uploading the edited dll file to my cloud server and see if the lag still occurs and hope db doesn't corrupt🤞

**Comment by Nimdy** [comment]
Increasing your resources without mods is not going to help. I guess my attempt to explain this above is not well spelled out.

Resources have nothing to do with the lag at this point and as you are aware the reason is the connection speed limitations currently in place.  These connection limitations are set to protect the database during its operational tasking.

Let me  know how it goes. 

Even though I understand why others are having lag issue, I have not experienced this myself. All my players use wired connections and avg 84ms - 180ms ping times to the server. 

For science, we had folks switch to a wifi connection and then we started to see some jumps in random lag spikes but normally just more noticeable during server auto saves.

I believe this to be a issue as well... Wireless connected players. UDP + Wireless = Loki

UDP + Wireless connections + Low system computers running the game = Loki 

Player Data:  
-Computer  Specs: CPU and GPU (integrated HD graphics cards = Loki)
-Connection Type:  Wired or Wireless (true wired not wired to wifi repeater...)
-Software on computers running (Antivirus, Firewalls, Malware..etc)
-Hardware:  Network Card (and software that is used to manage it)

Server:
Cloud Hosted
Home Hosted (ESXi, Proxmox, VM, Virtual Box)

Networking:
Basic networking information: NAT type, DoubleNAT...
Wired
Wireless
Hotspot (connecting to wireless hotspot)

Traceroutes from players connected to server. (How many hops...UDP packets and a lot of hops = Loki)


This is just me thinking... and I might just be full of crap.  However, I would like to know the data for science.

I am sure the DEVs are thinking about this stuff...

Thoughts
