### ISSUE TITLE
Installing Valheim with config data in a file

### ISSUE THREAD

**Issue by rako233** [Nimdy/Dedicated_Valheim_Server_Script#97]
Since I've installed Valheim more than one time, it would be great when the process of installation is reading the necessary data from a file, when such a file exist. Excluded should be the password for the steam user. Is the steam user existing, no password isn't necessary anyway.

**Comment by Nimdy** [comment]
that was completed and delete a long time ago.

You can pull it here: https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/d1b189b2667b11d114c9dbd455efdcff30f0c899/build_dedicated_valheim_server.sh

I am not giving support on this file any longer because of human error.  The script works and you can use it as you see fit.
